apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: studyflow

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: studyflow-backend:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: backend-config

          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD