apiVersion: v1
kind: ConfigMap

metadata:
  name: backend-config
  namespace: studyflow

data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/studyflow
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_SQL_INIT_MODE: never
  SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "false"
  SPRING_H2_CONSOLE_ENABLED: "false"